### ISSUE TITLE
`quarto env` no more exists

### ISSUE THREAD

**Issue by cderv** [pommevilla/quarto-action-tests#1]
From https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/runs/3050529723
fixed by https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/commit/8c37422c374090314ec0a416b4650ecbcc9c8d49

Command has been removed https://github.com/quarto-dev/quarto-cli/commit/12540d42b6f89e0292bf8109d0b41c3ac7cfedfb

The test / demo workflow should be updated. 

Is this the right repo to notify ? :)

Opening here so that we don't forget

**Comment by pommevilla** [comment]
Thanks for this, @cderv! 

I've actually moved everything relating to the github action to [https://github.com/pommevilla/quarto-render](https://github.com/pommevilla/quarto-render). This won't affect the published action since that action currently only installs Quarto and renders the documents. I'll eventually add in `quarto check` as a diagnostic/debug option, but for right now, there's no problem.
